"""add relationship (o2m) for tables

Revision ID: ecdcdc4db1fd
Revises: aa1d78367623
Create Date: 2020-09-29 16:07:20.324382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdcdc4db1fd'
down_revision = 'aa1d78367623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    # ### end Alembic commands ###
